version: '3'
services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - ./.config/dev/postgres.dev.env
    networks:
      - backend

  redis:
    image: 'redis:latest'
    networks:
      - backend

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      backend:
        aliases:
          - client

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./.config/dev/api.dev.env
    networks:
      backend:
        aliases:
          - api

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    depends_on:
      - redis
    volumes:
      - ./worker:/app
      - /app/node_modules
    env_file:
      - ./.config/dev/worker.dev.env
    networks:
      - backend

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
